import type { Metadata } from "next";
import { breadcrumbSchema, businessSchema, graphSchema, siteUrl } from "../seo";

const url = `${siteUrl}/team/`;
export const metadata: Metadata = { title: "Team | Immobilienmakler Leverkusen", description: "Das Team von Stark & Hoffmann Immobilien in Leverkusen: persönliche Ansprechpartner für Immobilienbewertung, Verkauf und Vermietung.", alternates: { canonical: url }, openGraph: { title: "Unser Team | Stark & Hoffmann Immobilien Leverkusen", description: "Ihre persönlichen Ansprechpartner in Leverkusen.", url }, twitter: { card: "summary" } };

// Öffentliche Evernest-Standortseite, geprüft am 30.08.2026.
const team: { name: string; role: string; areas: string; bio: string; image?: string; profile?: string }[] = [
  { name: "Patrick Stark", role: "Lizenzpartner", areas: "Bergisch Gladbach, Leverkusen, Köln-Dellbrück", bio: "Aufgewachsen in einer Handwerkerfamilie, bringt er fundiertes Wissen zu Baustruktur und Architektur mit. Er arbeitet transparent statt im Blindflug und behält im Blick, dass hinter einem Verkauf fast immer eine persönliche Lebenssituation steht.", image: "patrick.jpg", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/patrick-stark/" },
  { name: "Julian Hoffmann", role: "Lizenzpartner", areas: "Bergisch Gladbach, Leverkusen, Köln-Dellbrück", bio: "Betriebswirtschaftliches Studium und Vertriebserfahrung aus mehreren Branchen, auch international. Sein Anspruch: ein Verkaufsprozess, der professionell und transparent läuft und in dem Vertrauen, Kommunikation und Verlässlichkeit tragen.", image: "julian.jpg", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/julian-hoffmann/" },
  { name: "Johannes Brauns", role: "Teamlead Acquisition", areas: "Bergisch Gladbach, Leverkusen", bio: "Seit über 20 Jahren in der Immobilienbranche und als gebürtiger Rheinländer mit dem regionalen Markt vertraut. Als erster Ansprechpartner lernt er Eigentümer kennen, erkennt Potenziale und bereitet den Verkauf strukturiert vor.", image: "johannes.jpg", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/johannes-brauns/" },
  { name: "Vanessa Rogge", role: "Assistenz der Geschäftsführung", areas: "Bergisch Gladbach, Leverkusen, Köln-Dellbrück", bio: "Unterstützt die Geschäftsführung und hält die organisatorischen Abläufe im Team zusammen.", image: "vanessa.jpg" },
  { name: "Doreen Kaschner", role: "Operations & Marketing Managerin", areas: "Bergisch Gladbach, Leverkusen, Köln-Dellbrück", bio: "Koordiniert die operativen Prozesse und das Marketing des Teams.", image: "doreen.jpg" },
  { name: "Noah Ginczek", role: "Selbständiger Immobilienmakler", areas: "Leverkusen", bio: "Betreut als selbständiger Immobilienmakler Eigentümer in Leverkusen.", image: "noah.jpg" },
  { name: "Christian Engelke", role: "Selbstständiger Immobilienmakler", areas: "Bergisch Gladbach, Leverkusen", bio: "Kam aus der IT-Branche, zuletzt als Produktmanager, in die Immobilienberatung. Seit 2014 hat er selbst mehrere vermietete Immobilien erworben — Kauf, Vermietung und Verwaltung kennt er aus eigener Praxis.", image: "christian.jpg", profile: "https://www.evernest.com/de/unsere-makler/bergisch-gladbach/christian-engelke/" },
  { name: "Robin Köppe", role: "Selbstständiger Immobilienmakler", areas: "Bergisch Gladbach, Leverkusen", bio: "Gebürtiger Leverkusener und ehemaliger 800-Meter-Läufer bei TSV Bayer 04. Nach 25 Jahren in verantwortlichen Vertriebspositionen setzt er auf persönlichen Austausch, ehrliche Beratung und verlässliche Begleitung.", image: "robin.jpg", profile: "https://www.evernest.com/de/unsere-makler/leverkusen/robin-koeppe/" },
  { name: "Sebastian Schulz-Dobrick", role: "Selbstständiger Immobilienmakler", areas: "Leverkusen", bio: "Hat selbst viele Jahre in Leverkusen gelebt und kennt die Unterschiede zwischen Schlebusch, Opladen und Wiesdorf. Er hört genau hin, stellt die richtigen Fragen und legt Wert auf ehrliche, durchdachte Lösungen.", image: "sebastian.jpg", profile: "https://www.evernest.com/de/unsere-makler/leverkusen/sebastian-schulz/" },
];

export default function TeamPage() {
  const schema = graphSchema(businessSchema, breadcrumbSchema([{ name: "Startseite", url: `${siteUrl}/` }, { name: "Team", url }]), ...team.map(({ name, role, ...person }) => ({ "@type": "Person", name, jobTitle: role, worksFor: { "@id": `${siteUrl}/#immobilienmakler` }, ...("profile" in person ? { sameAs: person.profile } : {}) })));
  return <main className="team-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="site-header"><a className="brand" href="/" aria-label="Startseite"><span className="brand-mark">S<span>&</span>H</span><span><strong>Stark &amp; Hoffmann</strong><small>Immobilien · Leverkusen</small></span></a><nav aria-label="Hauptnavigation"><a href="/#profil">Profil</a><a href="/team/">Team</a><a href="/#markt">Markt</a><a href="/#fahrplan">Verkaufsfahrplan</a><a href="/#staedte">Region</a><a href="/#faq">FAQ</a></nav><a className="header-cta" href="/immobilienbewertung/">Kostenlose Bewertung</a></header>
    <section className="team-hero"><div><p className="eyebrow light">Stark &amp; Hoffmann Immobilien</p><h1>Unser Team in Leverkusen.</h1><p>Persönliche Ansprechpartner, lokale Marktkenntnis und ein gemeinsames Ziel: Eigentümer vom ersten Gespräch bis zum erfolgreichen Abschluss verlässlich zu begleiten.</p></div></section>
    <section className="team-content section"><div className="section-head"><div><p className="eyebrow">Menschen vor Ort</p><h2>Das Team hinter Stark &amp; Hoffmann.</h2></div><p>Wir verbinden persönliche Beratung mit professioneller Bewertung, Vermarktung und Verkaufsbegleitung in Leverkusen und der Region.</p></div><figure className="team-photo"><img src="/team/team-leverkusen.jpg" alt="Team von Stark und Hoffmann Immobilien in Leverkusen" /></figure><div className="team-grid">{team.map(person => <article className="team-card" key={person.name}>{"image" in person ? <img src={`/team/${person.image}`} alt={`${person.name}, ${person.role}`} loading="lazy" /> : <div className="team-placeholder" aria-hidden="true"><span>{person.name.split(" ").map(part => part[0]).join("")}</span></div>}<div><h3>{person.name}</h3><p className="team-role">{person.role}</p><p className="team-areas">{person.areas}</p><p className="team-bio">{person.bio}</p>{person.profile && <a className="team-profile-link" href={person.profile} target="_blank" rel="noreferrer">Profil und Quelle bei Evernest ↗</a>}</div></article>)}</div><p className="team-source">Teamstand geprüft am 30. August 2026.</p></section>
    <section className="district-contact section"><div><p className="eyebrow light">Persönlich kennenlernen</p><h2>Sprechen wir über Ihre Immobilie.</h2><p>Unser Team begleitet Sie bei Bewertung, Verkauf und Vermietung in Leverkusen – im Showroom am Wiesdorfer Platz oder telefonisch.</p></div><div><a className="button gold" href="/immobilienbewertung/">Bewertung starten</a><a href="tel:+4922049147881">+49 2204 914 7881</a></div></section>
    <footer><div className="footer-brand"><span className="brand-mark">S<span>&</span>H</span><div><strong>Stark &amp; Hoffmann Immobilien</strong><small>Evernest Lizenzpartner Leverkusen</small></div></div><div><h4>Kontakt</h4><p>Wiesdorfer Platz 19<br/>51373 Leverkusen</p><a href="tel:+4922049147881">+49 2204 914 7881</a><a href="mailto:leverkusen@evernest.com">leverkusen@evernest.com</a></div><div><h4>Unternehmen</h4><a href="/">Leverkusen</a><a href="https://www.evernest.com/de/unsere-makler/leverkusen/" target="_blank" rel="noreferrer">Evernest Leverkusen</a><a href="/impressum/">Impressum</a><a href="/datenschutz/">Datenschutz</a></div><div><h4>Rechtliches</h4><p>Stark &amp; Hoffmann Immobilien GmbH<br/>Amtsgericht Köln, HRB 116396<br/>Geschäftsführer: Patrick Stark, Julian Hoffmann</p></div></footer>
    <div className="copyright">© 2026 Stark &amp; Hoffmann Immobilien GmbH · Alle Angaben unverbindlich. Irrtümer und Änderungen vorbehalten.</div>
  </main>;
}
