// Häufige Fragen – seit dem Umzug auf /ratgeber/ nicht mehr auf der Startseite.
export const faq: Array<[string, string]> = [
  ["Wie viel ist meine Immobilie in Leverkusen wert?", "Das hängt von Straße und [Stadtteil](/#staedte) ab, vom Grundstück, von Baujahr, Zustand und Energiebilanz sowie von der aktuellen Nachfrage. Unsere [Online-Bewertung](/immobilienbewertung/) gibt einen ersten Anhaltspunkt; belastbar wird der Wert erst, wenn wir Objekt und Umfeld vor Ort gesehen haben."],
  ["Wann ist der richtige Zeitpunkt für einen Verkauf in Leverkusen?", "Neben der Marktlage zählen Ihre eigenen Pläne, eine womöglich noch laufende Spekulationsfrist und der Zustand der Immobilie. Ausschlaggebend ist, wie Angebot und Nachfrage im jeweiligen [Stadtteil](/#staedte) gerade zueinander stehen."],
  ["Muss ich einen Makler beauftragen – und was kostet er?", "Pflicht ist ein Makler nicht. Er übernimmt [Bewertung](/immobilienbewertung/), Unterlagen, Vermarktung, die Auswahl der Interessenten, die Verhandlung und die Vorbereitung beim Notar. Die Provision wird vor dem Auftrag offen vereinbart; für Wohnungen und Einfamilienhäuser regelt das Gesetz, wie die [Maklerkosten](/ratgeber/maklerkosten-beim-immobilienkauf/) verteilt werden."],
  ["Wie lange dauert es, eine Immobilie in Leverkusen zu verkaufen?", "Das hängt von Objektart, Preis, Unterlagen und Nachfrage ab. Ist alles vorbereitet, folgen Vermarktung, Besichtigungen, die Prüfung der Finanzierung und der Notartermin. Ein realistischer Preis und von Anfang an vollständige Unterlagen machen den Weg in der Regel deutlich kürzer."],
  ["Welche Unterlagen brauche ich, wenn ich mein Haus verkaufe?", "Meist Grundbuchauszug, [Flurkarte](/ratgeber/flurkarte/), Bauunterlagen, eine Berechnung von Wohn- und Nutzfläche, Grundrisse, den Energieausweis und Belege über Modernisierungen. Bei einer Eigentumswohnung kommen etwa Teilungserklärung, [Wirtschaftsplan](/ratgeber/wirtschaftsplan/), Versammlungsprotokolle und Angaben zur Erhaltungsrücklage hinzu."],
  ["Ist ein Energieausweis beim Verkauf Pflicht?", "In den meisten Fällen ja. Liegt ein Energieausweis vor, gehören seine Pflichtangaben schon in die Anzeige; spätestens bei der Besichtigung muss er vorgelegt werden. Welche Ausweisart nötig ist, richtet sich nach dem Gebäude."],
  ["Was ändert sich, wenn die Immobilie vermietet ist?", "Vermietete Objekte kaufen vor allem Kapitalanleger; für sie zählen die dauerhaft erzielbare Miete und die Rendite. Leerstehende Häuser und Wohnungen sind zusätzlich für Selbstnutzer interessant. Mietvertrag, Miethöhe und die rechtliche Lage bestimmen deshalb, wer als Käufer infrage kommt und welcher Preis erzielbar ist."],
  ["Fallen beim Verkauf Steuern an?", "Das kommt auf den Einzelfall an – etwa auf die Haltedauer, eine Eigennutzung, den Veräußerungsgewinn und die Zahl früherer Verkäufe. Bei geerbten Immobilien kann die Besitzzeit des Erblassers mitzählen. Klären Sie steuerliche Fragen vor dem Verkauf mit Ihrer Steuerberatung."],
  ["Was ist beim Verkauf eines geerbten Hauses zu beachten?", "Zuerst sollten Eigentumsverhältnisse, Grundbuch und eventuelle Belastungen geklärt sein. In einer Erbengemeinschaft müssen alle Beteiligten den Verkauf mittragen. Wichtig sind außerdem steuerliche Fristen, der Zustand des Hauses und eine neutrale [Bewertung](/immobilienbewertung/)."],
  ["Was sagt der Bodenrichtwert in Leverkusen aus?", "Der [Bodenrichtwert](/bodenrichtwert-leverkusen/) ist ein amtlicher Anhaltswert für ein typisches unbebautes Grundstück in seiner Richtwertzone. Für Bauland hat der [Gutachterausschuss](/gutachterausschuss-leverkusen/) in Leverkusen 337 solcher Werte beschlossen. Zuschnitt, Erschließung, Topografie, Bebauung und Mikrolage können den Wert eines konkreten Grundstücks deutlich verschieben."],
  ["Wie wichtig ist der Stadtteil für den Preis?", "Sehr wichtig. Wiesdorf, Opladen, Schlebusch, Hitdorf und die übrigen [Stadtteile](/#staedte) unterscheiden sich bei Bodenpreisen, Bebauung und Nachfrage. Und selbst im selben Stadtteil verändern Straße, Ausblick, Verkehrslage, Grundstückszuschnitt und Richtwertzone den Wert."],
  ["Wie funktioniert die kostenlose Bewertung?", "Sie geben Adresse und Eckdaten ein. Wir ordnen die Immobilie ihrem [Stadtteil](/#staedte) und der Marktlage zu, prüfen Grundstück und Gebäudemerkmale und besprechen danach die realistische Preisspanne und die nächsten Schritte – unverbindlich."],
  ["Welche Fehler kosten beim Hausverkauf Geld?", "Typisch sind ein Angebotspreis ohne nachvollziehbare Begründung, lückenhafte Unterlagen, schwache Fotos und Grundrisse, nicht geprüfte Interessenten und zu schnelle Preisnachlässe. Bekannte Mängel sollten offen dokumentiert sein, damit der Verkauf rechtlich sauber vorbereitet ist."],
  ["Geht ein Verkauf auch diskret, ohne Immobilienportal?", "Ja. Dann bieten wir die Immobilie zunächst gezielt Interessenten an, die bei uns vorgemerkt und geprüft sind. Ob das passt, hängt von Objekt, Lage, Zielgruppe und Ihrem Zeitplan ab."],
];
