import Link from "next/link"; import {DistrictGrid,PageShell} from "./components"; import {market,official} from "./data";
const steps=[["01","Bewertung & Erstgespräch","Wir erfassen Lage, Zustand, Baujahr, Energieeffizienz und verfügbare Unterlagen."],["02","Verkaufsstrategie","Ziel, Zeitrahmen, Angebotspreis und Vermarktungsweg werden nachvollziehbar abgestimmt."],["03","Vorbereitung","Wir koordinieren Unterlagen, Grundrissaufbereitung, Fotografie und Exposé."],["04","Vermarktung","Die Immobilie wird passend zur Zielgruppe über ausgewählte Kanäle angeboten."],["05","Besichtigung & Prüfung","Termine, Rückfragen und Bonitätsnachweise werden strukturiert begleitet."],["06","Notar & Übergabe","Wir unterstützen bei Verhandlung, Vertragsvorbereitung und dokumentierter Übergabe."]];
export default function Home(){return <PageShell><main>
<section className="hero"><div><p className="eyebrow">Ihre Immobilienmakler in Leverkusen</p><h1>Immobilienmakler Leverkusen.<br/><em>Persönlich begleitet.</em></h1><p className="lead">Stark &amp; Hoffmann begleitet Eigentümer beim Verkauf und bei der Bewertung von Häusern, Wohnungen und Grundstücken in Leverkusen.</p><div className="actions"><Link className="button" href="/immobilienbewertung">Immobilie bewerten lassen</Link><a className="text-link" href="tel:+4922049147881">02204 914 7881 ↗</a></div><div className="tags"><span>Lokale Ansprechpersonen</span><span>Klare Prozesse</span><span>Digital unterstützt</span></div></div><div className="hero-art" aria-label="Abstrakte Architekturillustration"><div/><div/><div/></div></section>
<section className="section"><p className="eyebrow">Immobilie verkaufen in Leverkusen</p><h2>Welches Eigentum möchten Sie verkaufen?</h2><p className="intro">Objektart, Mikrolage und Dokumentation beeinflussen den passenden Verkaufsweg. Unsere Ratgeber ordnen die wichtigsten Schritte ein.</p><div className="cards"><Link href="/haus-verkaufen-leverkusen"><small>Verkaufsratgeber</small><b>Haus verkaufen</b><span>Bewertung, Unterlagen und Vermarktung →</span></Link><Link href="/wohnung-verkaufen-leverkusen"><small>Verkaufsratgeber</small><b>Wohnung verkaufen</b><span>Wohnungswert und Gemeinschaftsunterlagen →</span></Link><Link href="/grundstueck-verkaufen-leverkusen"><small>Verkaufsratgeber</small><b>Grundstück verkaufen</b><span>Bodenrichtwert und Baurecht einordnen →</span></Link></div></section>
<section id="profil" className="split dark"><div className="portrait-placeholder"><span>Leverkusen</span><b>Persönliche Beratung vor Ort</b></div><div><p className="eyebrow">Stark &amp; Hoffmann · Evernest Lizenzpartner</p><h2>Erfahrene Branchenkenner und Vertriebsprofis.</h2><p>Die öffentliche Evernest-Standortseite nennt Stark &amp; Hoffmann Immobilien GmbH als Lizenznehmer für Leverkusen. Patrick Stark und Julian Hoffmann werden dort als Lizenzpartner für Leverkusen geführt.</p><ul className="checklist"><li>Individuelle Immobilienbewertung</li><li>Zielgruppengerechte Vermarktung</li><li>Qualifizierung von Kaufinteressenten</li><li>Begleitung bis zum Abschluss</li></ul><Link className="button pale" href="/team">Team kennenlernen</Link></div></section>
<section className="section market"><p className="eyebrow">Immobilienmarkt Leverkusen</p><h2>Der amtliche Markt in Zahlen.</h2><p className="intro">Registrierte Transaktionen und Umsätze im Berichtsjahr {market.year}.</p><div className="metrics"><div><strong>{market.contracts}</strong><span>Kauffälle insgesamt</span></div><div><strong>{market.turnover}</strong><span>Umsatzvolumen</span></div><div><strong>{market.houses}</strong><span>Einfamilienhäuser</span></div><div><strong>{market.condominiums}</strong><span>Eigentumswohnungen</span></div></div><p className="source">Quelle: <a href={official.report}>{market.report}, S. 9–10 ↗</a></p><div className="market-links"><Link href="/gutachterausschuss-leverkusen">Gutachterausschuss</Link><Link href="/bodenrichtwert-leverkusen">Bodenrichtwerte</Link><Link href="/immobilienrichtwert-leverkusen">Immobilienrichtwerte</Link><Link href="/grundstuecksmarktbericht-leverkusen">Grundstücksmarktbericht</Link></div></section>
<section id="ablauf" className="section process"><p className="eyebrow">Verkaufsfahrplan</p><h2>In sechs Schritten zum Verkauf.</h2><div className="steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section id="stadtteile" className="section tinted"><p className="eyebrow">Leverkusen</p><h2>Alle 13 Stadtteile.</h2><p className="intro">Die Gliederung folgt den drei amtlichen Stadtbezirken der Stadt Leverkusen.</p><DistrictGrid/><p className="source">Quellen: <a href={official.districts}>Stadt Leverkusen – Stadtbezirke</a> · <a href={official.history}>Stadtgeschichte</a></p></section>
<section className="section faq"><p className="eyebrow">Häufige Fragen</p><h2>Was Eigentümer wissen möchten.</h2><details><summary>Was ist ein Bodenrichtwert?</summary><p>Der Gutachterausschuss beschreibt ihn als durchschnittlichen, aus Kaufpreisen abgeleiteten Lagewert des Bodens je Quadratmeter für ein Grundstück mit definiertem Zustand. Der konkrete Grundstückswert kann davon abweichen.</p></details><details><summary>Wo finde ich amtliche Werte für Leverkusen?</summary><p>Boden- und Immobilienrichtwerte werden kostenfrei über BORIS.NRW bereitgestellt. Für die Einordnung sind Richtwertzone, Stichtag und die Merkmale des jeweiligen Normobjekts wichtig.</p></details><details><summary>Ersetzt der Richtwert eine Immobilienbewertung?</summary><p>Nein. Richtwerte sind Orientierungshilfen. Zustand, Zuschnitt, Nutzungsmöglichkeiten, Rechte und Lasten sowie weitere Objektmerkmale müssen gesondert betrachtet werden.</p></details></section>
<section className="contact"><div><p className="eyebrow">Kontakt</p><h2>Sprechen wir über Ihre Immobilie.</h2><p>Unverbindlich, persönlich und ohne Zeitdruck – im Showroom am Wiesdorfer Platz oder telefonisch.</p></div><div className="contact-card"><b>Stark &amp; Hoffmann Immobilien GmbH</b><span>Wiesdorfer Platz 19<br/>51373 Leverkusen</span><a href="tel:+4922049147881">02204 914 7881</a><a href="mailto:leverkusen@evernest.com">leverkusen@evernest.com</a><Link className="button" href="/immobilienbewertung">Bewertung anfragen</Link></div></section>
</main></PageShell>}
