import type {Metadata} from "next"; import Link from "next/link"; import {notFound} from "next/navigation"; import {PageShell} from "../components"; import {market,official} from "../data"; import {breadcrumbSchema,businessSchema,faqSchema,graphSchema,siteUrl} from "../seo";
type Page={title:string;description:string;eyebrow:string;lead:string;body:React.ReactNode;faq?:Array<[string,string]>;figures?:boolean};
const pages:Record<string,Page>={
"immobilienmarkt-leverkusen":{title:"Immobilienmarkt Leverkusen 2025/2026",description:"Amtliche Zahlen zum Immobilienmarkt Leverkusen aus dem Grundstücksmarktbericht 2026.",eyebrow:"Amtliche Marktdaten",lead:"Der Grundstücksmarktbericht 2026 fasst das Berichtsjahr 2025 für das gesamte Stadtgebiet zusammen.",body:<><div className="facts"><div><strong>{market.contracts}</strong><br/>Kauffälle</div><div><strong>{market.turnover}</strong><br/>Umsatzvolumen</div><div><strong>{market.houses}</strong><br/>Einfamilienhäuser</div></div><h2>Einordnung</h2><p>54 Prozent der Kauffälle entfielen auf Wohnungs- und Teileigentum, 38 Prozent auf bebaute und 8 Prozent auf unbebaute Grundstücke. Diese amtlichen Gesamtmarktdaten sind keine Preisprognose für ein einzelnes Objekt.</p></>,faq:[["Wie viele Immobilien wurden 2025 in Leverkusen verkauft?","Der Gutachterausschuss zählt 1.195 Kauffälle mit einem Geldumsatz von rund 463 Millionen Euro. 54 Prozent entfielen auf Wohnungs- und Teileigentum, 38 Prozent auf bebaute und 8 Prozent auf unbebaute Grundstücke."],["Was kostet eine Eigentumswohnung in Leverkusen?","Bei Weiterverkäufen lag der mittlere Preis 2025 je nach Baujahr zwischen 2.444 und 3.495 Euro je Quadratmeter Wohnfläche. Wohnungen in Großwohnanlagen mit mehr als fünf Vollgeschossen bilden einen eigenen Teilmarkt mit 1.750 bis 2.120 Euro je Quadratmeter."]],figures:true},
"gutachterausschuss-leverkusen":{title:"Gutachterausschuss Leverkusen",description:"Aufgaben, Produkte und Kontakt des Gutachterausschusses für Grundstückswerte in Leverkusen.",eyebrow:"Neutrale Markttransparenz",lead:"Der Gutachterausschuss ist ein weisungsunabhängiges Kollegialgremium und für das Gebiet der Stadt Leverkusen zuständig.",body:<><h2>Aufgaben und Produkte</h2><p>Zu seinen Aufgaben gehören unter anderem die Führung und Auswertung der Kaufpreissammlung, die Ermittlung von Bodenrichtwerten und die Veröffentlichung des jährlichen Grundstücksmarktberichts.</p><div className="callout"><b>Geschäftsstelle</b><p>Hauptstraße 105, 51373 Leverkusen · gutachterausschuss@stadt.leverkusen.de</p></div></>,faq:[["Welche Aufgaben hat der Gutachterausschuss?","Er führt und wertet die Kaufpreissammlung aus, ermittelt die Bodenrichtwerte, veröffentlicht den jährlichen Grundstücksmarktbericht und erstattet Verkehrswertgutachten. Er ist ein weisungsunabhängiges Kollegialgremium."],["Wo erreiche ich die Geschäftsstelle?","Die Geschäftsstelle sitzt in der Hauptstraße 105, 51373 Leverkusen, und ist unter gutachterausschuss@stadt.leverkusen.de sowie telefonisch unter 0214 406 6263 erreichbar."]]},
"bodenrichtwert-leverkusen":{title:"Bodenrichtwert Leverkusen 2026",description:"Bodenrichtwerte Leverkusen verstehen und kostenfrei über BORIS.NRW abrufen.",eyebrow:"Stichtag 1. Januar 2026",lead:`Für Bauland beschloss der Gutachterausschuss ${market.landZones} Bodenrichtwerte in Leverkusen.`,body:<><h2>Was der Wert aussagt</h2><p>Der Bodenrichtwert ist ein durchschnittlicher Lagewert je Quadratmeter für den Boden eines definierten Richtwertgrundstücks. Er wird in Zonen ausgewiesen; Abweichungen des konkreten Grundstücks müssen sachgerecht berücksichtigt werden.</p><p><a className="button" href={official.boris}>BORIS.NRW öffnen ↗</a></p></>,faq:[["Wie viele Bodenrichtwerte gibt es in Leverkusen?","Zum Stichtag 1. Januar 2026 hat der Gutachterausschuss 337 Bodenrichtwerte für Bauland beschlossen."],["Was kostet Bauland in Leverkusen?","Die gebietstypischen Bodenrichtwerte liegen für freistehende Ein- und Zweifamilienhäuser bei 550 Euro je Quadratmeter in guter, 470 in mittlerer und 420 in einfacher Lage. Für Doppelhaushälften und Reihenendhäuser sind es 580 / 510 / 440 Euro, für Reihenmittelhäuser 600 / 520 / 450 Euro."]],figures:true},
"immobilienrichtwert-leverkusen":{title:"Immobilienrichtwert Leverkusen",description:"Amtliche Immobilienrichtwerte für Häuser und Wohnungen in Leverkusen richtig einordnen.",eyebrow:"Amtliche Orientierung",lead:"Immobilienrichtwerte sind durchschnittliche Lagewerte für Immobilien, bezogen auf ein festgelegtes Normobjekt.",body:<><h2>Vom Richtwert zum Objekt</h2><p>Die Werte werden aus der Kaufpreissammlung abgeleitet und beinhalten Bodenwert und bauliche Anlagen. BORIS.NRW stellt örtliche Fachinformationen und einen Immobilien-Preis-Kalkulator bereit. Ein individueller Verkehrswert entsteht daraus nicht automatisch.</p></>,faq:[["Auf welches Normobjekt beziehen sich die Immobilienrichtwerte?","Auf ein freistehendes Haus, Baujahr 1960 bis 1969, mit 500 bis 599 Quadratmetern Baulandfläche, 130 bis 139 Quadratmetern Wohnfläche, mittlerem Gebäudestandard, teilmodernisiert und einer Wohneinheit."],["Wo finde ich die Immobilienrichtwerte?","Kostenfrei über BORIS.NRW, zusammen mit den örtlichen Fachinformationen und einem Preis-Kalkulator. Im Grundstücksmarktbericht selbst sind sie nicht als Tabelle abgedruckt."]]},
"grundstuecksmarktbericht-leverkusen":{title:"Grundstücksmarktbericht Leverkusen 2026",description:"Grundstücksmarktbericht Leverkusen 2026: Kauffälle, Umsätze und amtliche Bewertungsdaten.",eyebrow:"Berichtsjahr 2025",lead:"Der Bericht stellt Umsatz- und Preisentwicklungen verschiedener Teilmärkte dar und enthält Daten für die Wertermittlung.",body:<><h2>Kostenfrei verfügbar</h2><p>Der Gutachterausschuss veröffentlicht den Bericht als PDF über GARS.NRW und BORIS.NRW. Die aktuelle Ausgabe trägt das Jahr 2026 und umfasst den Zeitraum 1. Januar bis 31. Dezember 2025.</p><a className="button" href={official.report}>Bericht als PDF öffnen ↗</a></>,faq:[["Welchen Zeitraum umfasst der Bericht 2026?","Das Berichtsjahr 2025, also den 1. Januar bis 31. Dezember 2025."],["Was kostet der Bericht?","Nichts. Der Gutachterausschuss veröffentlicht ihn kostenfrei als PDF über GARS.NRW und BORIS.NRW."]]},
"haus-verkaufen-leverkusen":{title:"Haus verkaufen Leverkusen",description:"Haus in Leverkusen verkaufen: Bewertung, Unterlagen, Vermarktung und sicherer Ablauf.",eyebrow:"Verkaufsratgeber",lead:"Ein Hausverkauf beginnt mit einer objektbezogenen Bewertung und vollständigen Unterlagen.",body:<><h2>Was wir prüfen</h2><p>Lage, Grundstück, Wohn- und Nutzfläche, Baujahr, Zustand, Modernisierungen und Energieeffizienz gehören ebenso zur Einordnung wie Grundbuch, Bauunterlagen und Rechte oder Lasten.</p></>,faq:[["Was wurde 2025 für Häuser in Leverkusen gezahlt?","Der Bericht zählt 344 Kauffälle über Ein- und Zweifamilienhäuser. Bei wiederverkauften freistehenden Einfamilienhäusern lagen die Medianpreise je nach Baujahr zwischen 450.000 und 530.000 Euro, bei Reihenhäusern zwischen 281.250 und 581.000 Euro."],["Welche Unterlagen werden für den Hausverkauf gebraucht?","Grundbuchauszug, Bauunterlagen und Flächenberechnungen, Energieausweis, Nachweise über Modernisierungen sowie Angaben zu Rechten und Lasten."]],figures:true},
"wohnung-verkaufen-leverkusen":{title:"Wohnung verkaufen Leverkusen",description:"Eigentumswohnung in Leverkusen verkaufen: Wert, WEG-Unterlagen und Käuferansprache.",eyebrow:"Verkaufsratgeber",lead:"Bei Eigentumswohnungen beeinflussen neben der Wohnung auch Gebäude und Gemeinschaftsunterlagen die Vorbereitung.",body:<><h2>Wichtige Unterlagen</h2><p>Typischerweise werden Teilungserklärung, Aufteilungsplan, Wirtschaftsplan, Jahresabrechnungen, Protokolle und Angaben zur Instandhaltungsrücklage benötigt.</p></>,faq:[["Wie viele Eigentumswohnungen wurden 2025 in Leverkusen verkauft?","590 Kauffälle entfielen auf Wohnungseigentum. Das sind 49 Prozent aller Kauffälle und damit der größte Teilmarkt."],["Welche Unterlagen werden für den Wohnungsverkauf gebraucht?","Teilungserklärung und Aufteilungsplan, Wirtschaftsplan, die letzten Jahresabrechnungen, Protokolle der Eigentümerversammlungen und Angaben zur Instandhaltungsrücklage."]],figures:true},
"grundstueck-verkaufen-leverkusen":{title:"Grundstück verkaufen Leverkusen",description:"Grundstück in Leverkusen verkaufen: Bodenrichtwert, Baurecht und Grundstücksmerkmale prüfen.",eyebrow:"Verkaufsratgeber",lead:"Der Bodenrichtwert ist ein Ausgangspunkt – Nutzung, Erschließung, Zuschnitt und Baurecht entscheiden mit.",body:<><h2>Amtliche Orientierung</h2><p>Die Richtwertzone und ihre Definition werden über BORIS.NRW geprüft. Für ein konkretes Grundstück sind unter anderem Entwicklungszustand, planungsrechtliche Situation und tatsächliche Eigenschaften gesondert einzuordnen.</p></>,faq:[["Wie wird der Bodenwert eines Grundstücks ermittelt?","Ausgangspunkt ist der Bodenrichtwert der Richtwertzone. Er wird über den veröffentlichten Umrechnungskoeffizienten an die Grundstücksgröße angepasst; der Bericht gibt dafür die Funktion KF = 231,226 − 21,392 × ln(Grundstücksfläche) an. Ein 450 Quadratmeter großes Grundstück erhält damit den Faktor 1,00, ein 1.000 Quadratmeter großes den Faktor 0,83."],["Wie viele unbebaute Baugrundstücke wurden 2025 verkauft?","30 Kauffälle betrafen Bauflächen für Ein- und Zweifamilienhäuser, das sind 2,5 Prozent aller Kauffälle im Stadtgebiet."]],figures:true},
"impressum":{title:"Impressum",description:"Impressum Stark & Hoffmann Immobilien Leverkusen.",eyebrow:"Rechtliches",lead:"Anbieterkennzeichnung",body:<><p>Stark &amp; Hoffmann Immobilien GmbH<br/>Schloßstraße 41, 51429 Bergisch Gladbach<br/>Amtsgericht Köln, HRB 116396<br/>Geschäftsführer: Patrick Stark, Julian Hoffmann</p><p>Leverkusener Showroom: Wiesdorfer Platz 19, 51373 Leverkusen</p></>}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const slug=(await params).slug;const p=pages[slug];return p?{title:p.title,description:p.description,alternates:{canonical:`${siteUrl}/${slug}/`}}:{}}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){
  const slug=(await params).slug; const p=pages[slug]; if(!p)notFound();
  const url=`${siteUrl}/${slug}/`;
  const schema=graphSchema(
    businessSchema,
    breadcrumbSchema([{name:"Startseite",url:`${siteUrl}/`},{name:p.title,url}]),
    ...(p.faq?[faqSchema(p.faq)]:[]),
  );
  return <PageShell>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
    <section className="page-hero">
      <p className="breadcrumbs"><Link href="/">Startseite</Link> / {p.title}</p>
      <p className="eyebrow light">{p.eyebrow}</p>
      <h1>{p.title}</h1>
      <p>{p.lead}</p>
    </section>
    <main className="page-content section">
      {p.body}
      {p.faq&&<><h2>Häufige Fragen</h2><div className="faq-grid">{p.faq.map(([q,a])=><details className="faq-item" key={q}><summary>{q}<span aria-hidden="true">+</span></summary><div><p>{a}</p></div></details>)}</div></>}
      {p.figures&&<p className="source">Zahlen: <a href={official.report}>Gutachterausschuss Leverkusen, Grundstücksmarktbericht 2026</a>.</p>}
      <Link className="button dark" href="/immobilienbewertung/">Persönliche Bewertung anfragen</Link>
    </main>
  </PageShell>}
