import type {Metadata} from "next"; import Link from "next/link"; import {notFound} from "next/navigation"; import {PageShell} from "../components"; import {market,official} from "../data"; import {siteUrl} from "../seo";
const pages:Record<string,{title:string;description:string;eyebrow:string;lead:string;body:React.ReactNode}>={
"immobilienmarkt-leverkusen":{title:"Immobilienmarkt Leverkusen 2025/2026",description:"Amtliche Zahlen zum Immobilienmarkt Leverkusen aus dem Grundstücksmarktbericht 2026.",eyebrow:"Amtliche Marktdaten",lead:"Der Grundstücksmarktbericht 2026 fasst das Berichtsjahr 2025 für das gesamte Stadtgebiet zusammen.",body:<><div className="facts"><div><strong>{market.contracts}</strong><br/>Kauffälle</div><div><strong>{market.turnover}</strong><br/>Umsatzvolumen</div><div><strong>{market.houses}</strong><br/>Einfamilienhäuser</div></div><h2>Einordnung</h2><p>54 Prozent der Kauffälle entfielen auf Wohnungs- und Teileigentum, 38 Prozent auf bebaute und 8 Prozent auf unbebaute Grundstücke. Diese amtlichen Gesamtmarktdaten sind keine Preisprognose für ein einzelnes Objekt.</p></>},
"gutachterausschuss-leverkusen":{title:"Gutachterausschuss Leverkusen",description:"Aufgaben, Produkte und Kontakt des Gutachterausschusses für Grundstückswerte in Leverkusen.",eyebrow:"Neutrale Markttransparenz",lead:"Der Gutachterausschuss ist ein weisungsunabhängiges Kollegialgremium und für das Gebiet der Stadt Leverkusen zuständig.",body:<><h2>Aufgaben und Produkte</h2><p>Zu seinen Aufgaben gehören unter anderem die Führung und Auswertung der Kaufpreissammlung, die Ermittlung von Bodenrichtwerten und die Veröffentlichung des jährlichen Grundstücksmarktberichts.</p><div className="callout"><b>Geschäftsstelle</b><p>Hauptstraße 105, 51373 Leverkusen · gutachterausschuss@stadt.leverkusen.de</p></div></>},
"bodenrichtwert-leverkusen":{title:"Bodenrichtwert Leverkusen 2026",description:"Bodenrichtwerte Leverkusen verstehen und kostenfrei über BORIS.NRW abrufen.",eyebrow:"Stichtag 1. Januar 2026",lead:`Für Bauland beschloss der Gutachterausschuss ${market.landZones} Bodenrichtwerte in Leverkusen.`,body:<><h2>Was der Wert aussagt</h2><p>Der Bodenrichtwert ist ein durchschnittlicher Lagewert je Quadratmeter für den Boden eines definierten Richtwertgrundstücks. Er wird in Zonen ausgewiesen; Abweichungen des konkreten Grundstücks müssen sachgerecht berücksichtigt werden.</p><p><a className="button" href={official.boris}>BORIS.NRW öffnen ↗</a></p></>},
"immobilienrichtwert-leverkusen":{title:"Immobilienrichtwert Leverkusen",description:"Amtliche Immobilienrichtwerte für Häuser und Wohnungen in Leverkusen richtig einordnen.",eyebrow:"Amtliche Orientierung",lead:"Immobilienrichtwerte sind durchschnittliche Lagewerte für Immobilien, bezogen auf ein festgelegtes Normobjekt.",body:<><h2>Vom Richtwert zum Objekt</h2><p>Die Werte werden aus der Kaufpreissammlung abgeleitet und beinhalten Bodenwert und bauliche Anlagen. BORIS.NRW stellt örtliche Fachinformationen und einen Immobilien-Preis-Kalkulator bereit. Ein individueller Verkehrswert entsteht daraus nicht automatisch.</p></>},
"grundstuecksmarktbericht-leverkusen":{title:"Grundstücksmarktbericht Leverkusen 2026",description:"Grundstücksmarktbericht Leverkusen 2026: Kauffälle, Umsätze und amtliche Bewertungsdaten.",eyebrow:"Berichtsjahr 2025",lead:"Der Bericht stellt Umsatz- und Preisentwicklungen verschiedener Teilmärkte dar und enthält Daten für die Wertermittlung.",body:<><h2>Kostenfrei verfügbar</h2><p>Der Gutachterausschuss veröffentlicht den Bericht als PDF über GARS.NRW und BORIS.NRW. Die aktuelle Ausgabe trägt das Jahr 2026 und umfasst den Zeitraum 1. Januar bis 31. Dezember 2025.</p><a className="button" href={official.report}>Bericht als PDF öffnen ↗</a></>},
"haus-verkaufen-leverkusen":{title:"Haus verkaufen Leverkusen",description:"Haus in Leverkusen verkaufen: Bewertung, Unterlagen, Vermarktung und sicherer Ablauf.",eyebrow:"Verkaufsratgeber",lead:"Ein Hausverkauf beginnt mit einer objektbezogenen Bewertung und vollständigen Unterlagen.",body:<><h2>Was wir prüfen</h2><p>Lage, Grundstück, Wohn- und Nutzfläche, Baujahr, Zustand, Modernisierungen und Energieeffizienz gehören ebenso zur Einordnung wie Grundbuch, Bauunterlagen und Rechte oder Lasten.</p></>},
"wohnung-verkaufen-leverkusen":{title:"Wohnung verkaufen Leverkusen",description:"Eigentumswohnung in Leverkusen verkaufen: Wert, WEG-Unterlagen und Käuferansprache.",eyebrow:"Verkaufsratgeber",lead:"Bei Eigentumswohnungen beeinflussen neben der Wohnung auch Gebäude und Gemeinschaftsunterlagen die Vorbereitung.",body:<><h2>Wichtige Unterlagen</h2><p>Typischerweise werden Teilungserklärung, Aufteilungsplan, Wirtschaftsplan, Jahresabrechnungen, Protokolle und Angaben zur Instandhaltungsrücklage benötigt.</p></>},
"grundstueck-verkaufen-leverkusen":{title:"Grundstück verkaufen Leverkusen",description:"Grundstück in Leverkusen verkaufen: Bodenrichtwert, Baurecht und Grundstücksmerkmale prüfen.",eyebrow:"Verkaufsratgeber",lead:"Der Bodenrichtwert ist ein Ausgangspunkt – Nutzung, Erschließung, Zuschnitt und Baurecht entscheiden mit.",body:<><h2>Amtliche Orientierung</h2><p>Die Richtwertzone und ihre Definition werden über BORIS.NRW geprüft. Für ein konkretes Grundstück sind unter anderem Entwicklungszustand, planungsrechtliche Situation und tatsächliche Eigenschaften gesondert einzuordnen.</p></>},
"impressum":{title:"Impressum",description:"Impressum Stark & Hoffmann Immobilien Leverkusen.",eyebrow:"Rechtliches",lead:"Anbieterkennzeichnung",body:<><p>Stark &amp; Hoffmann Immobilien GmbH<br/>Schloßstraße 41, 51429 Bergisch Gladbach<br/>Amtsgericht Köln, HRB 116396<br/>Geschäftsführer: Patrick Stark, Julian Hoffmann</p><p>Leverkusener Showroom: Wiesdorfer Platz 19, 51373 Leverkusen</p></>},
"datenschutz":{title:"Datenschutz",description:"Datenschutzhinweise der Leverkusener Immobilienmakler-Website.",eyebrow:"Rechtliches",lead:"Hinweise zur Datenverarbeitung",body:<><p>Diese lokale Vorabversion setzt keine Analyse- oder Marketing-Cookies und bindet keine externen Schriften oder Trackingdienste ein. Vor einer Veröffentlichung ist die vollständige Datenschutzerklärung des Verantwortlichen einzusetzen und rechtlich zu prüfen.</p></>}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const slug=(await params).slug;const p=pages[slug];return p?{title:p.title,description:p.description,alternates:{canonical:`${siteUrl}/${slug}/`}}:{}}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const p=pages[(await params).slug];if(!p)notFound();return <PageShell><main className="inner"><p className="breadcrumbs"><Link href="/">Startseite</Link> / {p.title}</p><p className="eyebrow">{p.eyebrow}</p><h1>{p.title}</h1><p className="lead">{p.lead}</p>{p.body}<p className="source">Marktdaten: <a href={official.report}>Gutachterausschuss Leverkusen, Grundstücksmarktbericht 2026</a>. Stadtinformationen: Stadt Leverkusen.</p><Link className="button" href="/immobilienbewertung">Persönliche Bewertung anfragen</Link></main></PageShell>}
